---

- name: Install f.lux
  homebrew_cask: name=flux state=present
  environment:
    HOMEBREW_CASK_OPTS: --appdir={{ cask_app_appdir }}
  notify: brew cask cleanup

- name: Set location
  command: defaults write org.herf.Flux {{ item }}
  with_items:
    - location -string "{{ flux_location }}"
    - locationTextField -string {{ flux_locationTextField }}
  notify:
    - killall Flux

- name: Set colour temperatures
  osx_defaults:
    domain: org.herf.Flux
    key: "{{ item.key }}"
    type: int
    value: "{{ item.value }}"
  with_items:
    - { key: 'lateColorTemp', value: {{ flux_lateColorTemp }} }
    - { key: 'nightColorTemp', value: {{ flux_nightColorTemp }} }
  notify:
    - killall Flux
