---

# Command uses `basename` to return only filenames (excludes paths)
# Source: http://superuser.com/a/620591
- name: Get list of .app files in /Applications
  command: find . -depth 1 -name "*.app" -exec basename {} \;
  args:
    chdir: /Applications
  register: installed_apps
  changed_when: false
  tags:
    - dock_items
    - login_items

- include: dock_items.yml
- include: login_items.yml
