---

# https://docs.travis-ci.com/user/reference/osx

os: osx

cache:
  directories:
    # TODO: Sadly this seems to have no effect.
    - $HOME/Library/Caches/pip
    - $HOME/Library/Caches/Homebrew

matrix:
  include:
    # macOS 10.13
    - osx_image: xcode9.3beta
    # macOS 10.11
    - osx_image: xcode7.3

install:
  - bash scripts/install_deps.sh
  - bash scripts/copy_example_files.sh
  - ansible-galaxy install -r requirements.yml --force

script:
  # Syntax check
  - ansible-playbook macsible.yml --syntax-check
  
  # Run Ansible playbook:
  # - Skip tasks/roles that we know cause issues in Travis
  - ansible-playbook macsible.yml --skip-tags "no_ci"
