---
os: osx

install:
  # Install pip
  - sudo easy_install pip
  # Install ansible
  - sudo pip install ansible
  # Check ansible version
  - ansible --version
  # Install Ansible Lint
  - sudo pip install ansible-lint
  # Install Ansible Galaxy dependencies
  - ansible-galaxy install -r deps.yml

script:
  # Basic syntax checks
  - ansible-playbook -i hosts plists.yml --syntax-check
  - ansible-playbook -i hosts main.yml --syntax-check
