---

# https://docs.travis-ci.com/user/osx-ci-environment

os: osx

# env:
#   - USER=danbohea HOME=/Users/danbohea

# TODO: Setting env vars still doesn't seem to actually make the difference I'm
# expecting. Next try passinging in "travis" as the unix_username when running
# any playbooks.

before_install:
  # Debugging info
  - ansible --version
  - whoami
  - pwd
  - cd /Users/ && ls -la
  - cd /Users/travis/ && ls -la

install:
  # Install pip
  - sudo easy_install pip
  # Install ansible
  # Keep this at 1.9.4 until the following issue is resolved:
  # https://github.com/ansible/ansible-modules-core/issues/2473
  - sudo pip install ansible==1.9.4
  # Install Ansible Lint
  - sudo pip install ansible-lint
  # Install Ansible Galaxy dependencies
  - ansible-galaxy install -r deps.yml

script:
  # Playbook syntax checks
  # - ansible-playbook -i hosts plists.yml --syntax-check
  # - ansible-playbook -i hosts main.yml --syntax-check

  # Playbook lint checks
  # https://github.com/willthames/ansible-lint
  # - ansible-lint plists.yml
  # - ansible-lint main.yml

  # Run Ansible playbook on host "mba" (preparatory tasks only):
  - ansible-playbook -i hosts main.yml --tags "prep" --limit mba --extra-vars "unix_username=travis"
