---

# https://docs.travis-ci.com/user/osx-ci-environment

os: osx

install:
  - bash init.sh
  # Debug: Print installed versions
  - pip --version
  - ansible --version
  # Install Ansible Lint
  - sudo pip install -q ansible-lint
  # Debug: Print Ansible facts
  # - ansible localhost -m setup

script:
  # Playbook syntax check
  - ansible-playbook mac.yml --syntax-check

  # Playbook lint check
  # https://github.com/willthames/ansible-lint
  # "resources" is excluded to sidestep warnings about use of curl & git etc.
  - ansible-lint -x resources mac.yml

  # Custom playbook test for use in development only:
  # - catches possible fails early
  # - tweak/uncomment as required
  # - ansible-playbook mac.yml --tags "duti"

  # Run Ansible playbook:
  # - Skip tasks/roles that we no cause issues in Travis.
  # - Skip roles that require Mac OS >= 10.10.
  # - Skip stage_5 roles as they don't *really* add much to the test.
  - ansible-playbook mac.yml --skip-tags "mac_os_10_10,no_ci,temp_no_ci,stage_5"
