---

# https://docs.travis-ci.com/user/osx-ci-environment

os: osx

env:
  - USER=danbohea
  - HOME=/Users/danbohea

install:
  # Install pip
  - sudo easy_install pip
  # Install ansible
  - sudo pip install ansible
  # Check ansible version
  - ansible --version
  # Install Ansible Lint
  - sudo pip install ansible-lint
  # Install Ansible Galaxy dependencies
  - ansible-galaxy install -r deps.yml

script:
  # Playbook syntax checks
  - ansible-playbook -i hosts plists.yml --syntax-check
  - ansible-playbook -i hosts main.yml --syntax-check

  # Playbook lint checks
  # https://github.com/willthames/ansible-lint
  # - ansible-lint plists.yml
  # - ansible-lint main.yml

  # Run Ansible playbook on host "mba" (preparatory tasks only):
  - ansible-playbook -i hosts main.yml --tags "prep" --limit mba
