---

# https://docs.travis-ci.com/user/osx-ci-environment

matrix:
  include:
    # macOS 10.12
    - os: osx
      osx_image: xcode8.3
    # macOS 10.11
    - os: osx
      osx_image: xcode7.3
    # macOS 10.10
    - os: osx
      osx_image: xcode6.4
  allow_failures:
    # macOS 10.10
    - osx_image: xcode6.4
  fast_finish: true

install:
  # Debug info
  - python --version
  # Run setup script
  - bash init.sh
  # Debug info
  - pip --version
  - ansible --version

script:
  # Playbook syntax check
  - ansible-playbook mac.yml --syntax-check
  # Run Ansible playbook:
  # - Skip tasks/roles that we know cause issues in Travis
  - ansible-playbook mac.yml --skip-tags "no_ci"
