---

# https://docs.travis-ci.com/user/osx-ci-environment

os: osx

install:
  # Install pip
  - sudo easy_install pip
  # Install ansible
  # Keep this at 1.9.4 until the following issue is resolved:
  # https://github.com/ansible/ansible-modules-core/issues/2473
  - sudo pip install ansible==1.9.4
  # Install Ansible Lint
  - sudo pip install ansible-lint
  # Install Ansible Galaxy dependencies
  - ansible-galaxy install -r deps.yml
  # Update Homebrew & formulae
  - brew update

script:
  # Playbook syntax checks
  - ansible-playbook -i hosts plists.yml --syntax-check
  - ansible-playbook -i hosts main.yml --syntax-check

  # Playbook lint checks
  # https://github.com/willthames/ansible-lint
  # - ansible-lint plists.yml
  # - ansible-lint main.yml

  # Run Ansible playbook on host "mba".
  # - Skip roles that cause CI issues.
  # - Skip roles that require Mac OS >= 10.10.
  # - Skip stage_5 roles as they don't *really* add much to the test.
  - ansible-playbook -i hosts main.yml --limit mba --extra-vars "unix_username=travis" --skip-tags "no_ci,mac_os_10_10,stage_5"
