---

# User credentials
# ------------------------------------------------------------------------------

unix_username: "danbohea"

# System
# ------------------------------------------------------------------------------

# "laptop" | "desktop"
system_type: "laptop"

# Paths
# ------------------------------------------------------------------------------

ext_prefs_path: "~/Dropbox/Mac/mac-setup"

ext_prefs_path_common: "{{ ext_prefs_path }}/common"

ext_prefs_path_desktop: "{{ ext_prefs_path }}/desktop"

ext_prefs_path_laptop: "{{ ext_prefs_path }}/laptop"

plist_source_dirs:
  - "{{ ext_prefs_path_common }}/app_settings/plists"
  - "{{ ext_prefs_path_desktop }}/app_settings/plists"
  - "{{ ext_prefs_path_laptop }}/app_settings/plists"

# cask_app
# ------------------------------------------------------------------------------

# TODO: Set again here for any other roles that may require it
# (e.g. quick_look_plugins).
cask_app_appdir: "/Applications"

cask_app_plist_source_dirs: "{{ plist_source_dirs }}"

# sketch
# ------------------------------------------------------------------------------

sketch_plugins_dir: "/Users/{{ unix_username }}/Library/Application Support/com.bohemiancoding.sketch3/Plugins"
