---
- name: Mac setup
  hosts: localhost
  connection: local

  vars_files:
    - config.yml

  roles:

    # Prep
    # --------------------------------------------------------------------------

    - { role: osx, tags: ["osx","prep"] }
    - { role: ssh, tags: ["ssh","prep"] }
    - { role: spelling, tags: ["spelling","prep"] }
    # Access to passwords for use in other installations
    - { name: "lastpass-cli", brew_install_options: "with-pinentry,with-doc", tags: ["lastpass_cli","prep"], role: brew_pkg }
    # Access to synced app settings
    - { role: dropbox, tags: ["dropbox","prep"] }
    # Better text editor
    - { role: atom, tags: ["atom","prep"] }
    # Quick-peak access to the contents of more text file formats
    - { role: quick_look_plugins, tags: ["quick_look_plugins","prep"] }

    # Stage 1: Essential day-to-day
    # --------------------------------------------------------------------------

    - { role: dotfiles, tags: ["dotfiles","stage_1","no_ci"] }
    - { role: duti, tags: ["duti","stage_1","no_ci"] }
    - { role: desktop_symlinks, tags: ["desktop_symlinks","stage_1","no_ci"] }
    - { role: time_machine, tags: ["time_machine","stage_1"] }
    - { role: google_chrome, tags: ["google_chrome","stage_1"] }
    - { role: moom, tags: ["moom","stage_1"] }
    - { role: flux, tags: ["flux","stage_1"] }
    - { role: evernote, tags: ["evernote","stage_1"] }
    - { name: "caffeine", tags: ["caffeine","stage_1","sudo"], role: cask_app }
    - { name: "alfred", tags: ["alfred","stage_1","sudo"], role: cask_app }
    - { name: "atext", role: cask_app, tags: ["atext","stage_1"] }
    - { role: path_finder, tags: ["path_finder","stage_1"] }
    # - { name: "bettertouchtool", tags: ["bettertouchtool","plist","stage_1"], role: cask_app, cask_app_plists: "com.hegenberg.BetterTouchTool.plist" } # TODO: Currently failing
    - { name: "the-unarchiver", tags: ["the_unarchiver","stage_1"], role: cask_app }
    - { name: "keyboard-maestro", tags: ["keyboard_maestro","stage_1","mac_os_10_10"], role: cask_app }
    - { name: "skype", role: cask_app, tags: ["skype","plist","stage_1"], cask_app_plists: "com.skype.skype.plist" }

    # Stage 2: Essential dev
    # --------------------------------------------------------------------------

    - { role: vagrant, tags: ["vagrant","stage_2","sudo"] }
    - { name: "virtualbox", tags: ["virtualbox","stage_2","sudo"], role: cask_app, cask_app_plists: "org.virtualbox.app.VirtualBox.plist" }
    - { role: git, tags: ["git","stage_2"] }
    - { name: "git-extras", tags: ["git_extras","stage_2"], role: brew_pkg }
    - { role: composer, tags: ["composer","stage_2"] }
    - { role: rbenv, tags: ["rbenv","stage_2","no_ci"] }
    - { role: node_pkgs, tags: ["node_pkgs","stage_2"] }
    - { role: pip_pkgs, tags: ["pip_pkgs","stage_2"] }
    - { name: "dash", tags: ["dash","plist","stage_2"], role: cask_app, cask_app_plists: "com.kapeli.dash.plist" }
    - { name: "iterm2", role: cask_app, tags: ["iterm2","plist","stage_2"], cask_app_plists: "com.googlecode.iterm2.plist" }
    - { name: "kaleidoscope", tags: ["kaleidoscope","stage_2"], role: cask_app }
    - { role: tower, tags: ["tower","stage_2"] }
    - { name: "sequel-pro", tags: ["sequel_pro","stage_2"], role: cask_app }
    - { name: "transmit", tags: ["transmit","stage_2"], role: cask_app }
    - { name: "imageoptim", tags: ["imageoptim","stage_2"], role: cask_app }
    - { role: sketch, tags: ["sketch","stage_2"] } # TODO: Add plists

    # Stage 3: Projects
    # --------------------------------------------------------------------------

    - { role: projects, tags: ["projects","stage_3"] }

    # Stage 4: Remaining apps
    # --------------------------------------------------------------------------
    - { role: transmission, tags: ["transmission","stage_4"] }
    - { name: "bfg", tags: ["bfg","stage_4"], role: brew_pkg }
    - { name: "tree", tags: ["tree","stage_4"], role: brew_pkg }
    - { name: "istat-menus", role: cask_app, tags: ["istat_menus","plist","stage_4"], cask_app_plists: ["com.bjango.istatmenus.plist","com.bjango.istatmenus5.extras.plist"] }
    - { name: "vmware-fusion", tags: ["vmware_fusion","stage_4"], role: cask_app, when: system_type == "desktop" }
    - { name: "firefox", tags: ["firefox","stage_4"], role: cask_app }
    - { name: "opera", tags: ["opera","stage_4"], role: cask_app }
    - { name: "opera-mobile-emulator", tags: ["opera_mobile_emulator","stage_4"], role: cask_app }

    # Stage 5: No-frills cask installed apps that CI can skip.
    # This makes for faster tests & keeps Travis log verbosity to a minimum.
    # --------------------------------------------------------------------------

    - { name: "handbrake", tags: ["handbrake","stage_5"], role: cask_app, when: system_type == "desktop" }
    - { name: "postbox", tags: ["postbox","stage_5"], role: cask_app, when: system_type == "desktop" }
    - { name: "google-hangouts", tags: ["google_hangouts","stage_5"], role: cask_app }
    - { name: "hazel", tags: ["hazel","stage_5"], role: cask_app }
    - { name: "cakebrew", tags: ["cakebrew","stage_5"], role: cask_app }
    - { name: "hipchat", tags: ["hipchat","stage_5"], role: cask_app }
    - { name: "limechat", tags: ["limechat","stage_5"], role: cask_app, cask_app_plists: "net.limechat.LimeChat.plist" }
    - { name: "daisydisk", tags: ["daisydisk","stage_5"], role: cask_app }
    - { name: "flash-player", tags: ["flash_player","stage_5"], role: cask_app }
    - { name: "google-drive", tags: ["google_drive","stage_5"], role: cask_app }
    - { name: "libreoffice", tags: ["libreoffice","stage_5"], role: cask_app }
    - { name: "name-mangler", tags: ["name_mangler","stage_5"], role: cask_app }
    - { name: "skitch", tags: ["skitch","stage_5"], role: cask_app }
    - { name: "vlc", tags: ["vlc","stage_5"], role: cask_app }
    - { name: "google-plus-auto-backup", role: cask_app, tags: ["google_plus_auto_backup","plist","stage_5"], cask_app_plists: "com.google.gpautobackup.plist" }
    - { name: "sketchup", role: cask_app, tags: ["sketchup","stage_5"] }
    - { name: "bartender", role: cask_app, tags: ["bartender","plist","stage_5"], cask_app_plists: "com.surteesstudios.Bartender.plist" }
    - { name: "doxie", tags: ["doxie","stage_5"], role: cask_app }
    - { name: "omnigraffle", tags: ["omnigraffle","stage_5"], role: cask_app }
    - { name: "appcleaner", tags: ["appcleaner","stage_5"], role: cask_app }
    - { role: steam, tags: ["steam","stage_5"] }
    - { name: "crashplan", tags: ["crashplan","stage_5","prompt"], role: cask_app }
