---

- name: Install Vagrant
  homebrew_cask: name=vagrant state=present
  environment:
    HOMEBREW_CASK_OPTS: --appdir={{ cask_app_appdir }}
  notify: brew cask cleanup

- name: Ensure ~/.ssh/ exists
  file:
    path: ~/.ssh
    state: directory

- name: SSH config for local Vagrant development
  blockinfile:
    dest: ~/.ssh/config
    content: "Host *.local\n  ForwardAgent yes"
    create: yes

# TODO: Make idempotent
- name: Install Vagrant plugins
  command: vagrant plugin install {{ item }}
  with_items: "{{ vagrant_plugins }}"
