---

- name: Clone dotfiles repo to {{ dotfiles_dest }}
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest }}"
    accept_hostkey: yes

- name: Create symlinks to files in {{ dotfiles_dest }}
  file:
    path: ~/{{ item }}
    src: "{{ dotfiles_dest }}/{{ item }}"
    state: link
  with_items: {{ dotfiles_files }}

- name: Reload .bash_profile
  shell: source ~/.bash_profile
  changed_when: false
