---

- name: Clone dotfiles repo to {{ dotfiles_dir }}
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    version: master
    accept_hostkey: yes

- name: Create symlinks to files in {{ dotfiles_dir }}
  file:
    path: ~/{{ item }}
    src: "{{ dotfiles_dir }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles_files }}"

- name: Reload .bash_profile
  shell: source ~/.bash_profile
  changed_when: false
