---

- name: Clone dotfiles repo to {{ dotfiles_dir }}
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dir }}"
    version: master
    accept_hostkey: yes

# Command uses `basename` to return only filenames (excludes paths)
# Source: http://superuser.com/a/620591
- name: Get list of file names to symlink to
  command: find . -type f -depth 1 -name ".*" -exec basename {} \;
  args:
    chdir: "{{ dotfiles_dir }}"
  register: dotfiles_to_symlink
  changed_when: false

- name: Create symlinks to files in {{ dotfiles_dir }}
  file:
    path: ~/{{ item }}
    src: "{{ dotfiles_dir }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ dotfiles_to_symlink.stdout_lines }}"

- name: Reload .bash_profile
  shell: source ~/.bash_profile
  changed_when: false
