---

- name: Install Steam
  homebrew_cask: name=steam state=present
  environment:
    HOMEBREW_CASK_OPTS: --appdir={{ cask_app_appdir }}
  when: system_type == "desktop"
  notify: brew cask cleanup

- name: Remove default Steam directrory prior to creating symlink (desktop)
  file:
    path: "~/Library/Application Support/Steam"
    state: absent
  when: system_type == "desktop"

- name: Create symlink for Steam directory (desktop)
  file:
    path: "~/Library/Application Support/Steam"
    src: /Volumes/Data/Steam/
    state: link
    force: yes
  when: system_type == "desktop"
