---

- name: Set the icon size of Dock items
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 30
  notify:
    - killall Dock

- name: Set Dock orientation
  command: defaults write com.apple.dock orientation -string "left"
#   osx_defaults:
#     domain: com.apple.dock
#     key: orientation
#     type: string
#     value: "left"
  notify:
    - killall Dock

- name: Automatically hide and show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify:
    - killall Dock

# - name: Add applications to Dock
#   command: defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/{{ item }}.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
#   with_items:
#     - Atom
#     - Dropbox
#   notify:
#     - killall Dock
