---

- name: Install Sketch & supporting tools
  homebrew_cask: name={{ item }} state=present
  environment:
    HOMEBREW_CASK_OPTS: --appdir={{ cask_app_appdir }}
  with_items: "{{ sketch_apps }}"
  notify: brew cask cleanup

- name: Ensure Sketch plugins directory exists
  file:
    path: "{{ sketch_plugins_dir }}"
    state: directory

# TODO: Determine dest from end of item.repo
- name: Clone plugins to Sketch plugins directory
  git:
    repo: "{{ item.repo }}"
    dest: "{{ sketch_plugins_dir }}/{{ item.dest }}"
    depth: 1
    version: master
  with_items: "{{ sketch_plugin_repos }}"
