---

- name: Install Git
  homebrew: name=git
  notify: brew cleanup

# TODO: Make these config commands idempotent by checking ~.gitconfig first.

- name: Configure push.default
  command: git config --global push.default simple
  changed_when: false

- name: Configure user.name
  command: git config --global user.name "{{ git_user_name }}"
  changed_when: false

- name: Configure user.email
  command: git config --global user.email "{{ git_user_email }}"
  changed_when: false

# ------------------------------------------------------------------------------

- name: get git username
  shell: git config --global --get user.name
  register: git_user_name_result
  changed_when: False
  ignore_errors: yes

- name: get git user email
  shell: git config --global --get user.email
  register: git_user_email_result
  changed_when: False
  ignore_errors: yes

- name: set git username
  shell: git config --global user.name "{{git_user_name}}"
  when: git_user_email_result.stdout != "{{git_user_name}}"

- name: set git user email
  shell: git config --global user.email "{{git_user_email}}"
  when: git_user_email_result.stdout != "{{git_user_email}}"
