---

- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  args:
    creates: /usr/local/bin/brew

# The homebrew module's "update_homebrew" option seems to update homebrew
# for every package which is unnecessarily slow.
# Instead we just do it once right here.
- name: Update and upgrade homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: Tap the cask repository
  homebrew_tap: tap=caskroom/cask
