---

# TODO: The file module won't expand ~/ so we need a more robust way of checking for these directories.
# - name: Ensure required directories are present
#   file:
#     path: "{{ item }}/app_settings/plists"
#     state: directory
#   with_items:
#     - {{ common }}
#     - {{ desktop }}
#     - {{ laptop }}

# TODO: Add Ansible version check. The following tasks require >= Ansible 1.9.1.

# Gathering stats on local plist files will ensure that Ansible only attempts to copy files that actually exist
# (otheriwse it would fail)

- name: Gather stats on local plist files (common)
  stat: path=/Users/{{ unix_username }}/Library/{{ item }}
  with_items: {{ plists_common }}
  register: local_plists_common

- name: Gather stats on local plist files (system specific)
  stat: path=/Users/{{ unix_username }}/Library/{{ item }}
  with_items: {{ plists_system_specific }}
  register: local_plists_system_specific

# Copy plist files that exist on current system to synced storage

- name: Copy common plists
  copy:
    src: "{{ item.stat.path }}"
    dest: "{{ ext_prefs_path_common }}/app_settings/plists"
  with_items: {{ local_plists_common.results }}
  when: item.stat.exists
  tags: common

- name: Copy system specific plists
  copy:
    src: "{{ item.stat.path }}"
    dest: "{{ ext_prefs_path }}/{{ system_type }}/app_settings/plists"
  with_items: {{ local_plists_system_specific.results }}
  when: item.stat.exists
  tags: system
