---

- name: Install duti
  homebrew: name=duti
  notify: brew cleanup

# NOTE: ~/.duti should be provided by the dotfiles role

- name: Check that ~/.duti exists
  file:
    path: ~/.duti
    state: file
    follow: yes

# NOTE: The osx role *appears* to undo what duti has setup for us here but a
# restart should sort it out :)

- name: Run duti with preferences file
  shell: duti ~/.duti
