---

- name: Show the main window when launching Activity Monitor
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: OpenMainWindow
    type: bool
    value: true
  notify:
    - killall

- name: Show all processes in Activity Monitor
  osx_defaults:
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    type: int
    value: 0
  notify:
    - killall
