---

- name: Set the icon size of Dock items
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 30
  notify:
    - killall

# - name: Set dock orientation to "Left"
#   osx_defaults:
#     domain: com.apple.dock
#     key: orientation
#     type: string
#     value: "left"
#   notify:
#     - killall

- name: Automatically hide and show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify:
    - killall

- name: Speed up Mission Control animations
  osx_defaults:
    domain: com.apple.dock
    key: expose-animation-duration
    type: float
    value: 0.15
  notify:
    - killall

- name: Don’t automatically rearrange Spaces based on most recent use
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false
  notify:
    - killall
