---

- name: Set HOME as the default location for new Finder windows
  shell: defaults write com.apple.finder {{ item }}
  with_items:
    - NewWindowTarget -string "PfLo"
    - NewWindowTargetPath -string "file://${HOME}/"
  notify:
    - killall Finder

- name: "Finder: {{ item.name }}"
  osx_defaults:
    domain: com.apple.finder
    key: "{{ item.key }}"
    type: bool
    value: true
  with_items:
    - { name: 'Show icons for hard drives, servers, and removable media on the desktop', key: 'ShowExternalHardDrivesOnDesktop'}
    - { name: 'Show icons for hard drives, servers, and removable media on the desktop', key: 'ShowHardDrivesOnDesktop'}
    - { name: 'Show icons for hard drives, servers, and removable media on the desktop', key: 'ShowMountedServersOnDesktop'}
    - { name: 'Show icons for hard drives, servers, and removable media on the desktop', key: 'ShowRemovableMediaOnDesktop'}
    - { name: 'Show hidden files by default', key: 'AppleShowAllFiles'}
  notify:
    - killall Finder
