---

- name: Gather stats on all possible plist file locations
  stat: path={{ item[0] }}/{{ item[1] }}
  with_nested:
    - osx_plist_source_dirs
    - osx_plists
  register: osx_plist_files
  when: item[0] != ""

# Only copies items where a source file actually exists.
- name: Copy plist files to ~/Library/Preferences
  copy:
    src: "{{ item[0].stat.path }}"
    dest: ~/Library/Preferences/{{ item[1] }}
  with_nested:
    - osx_plist_files.results
    - osx_plists
  when: item[0].stat.path is defined

# TODO: Check if source image is there first.
# TODO: Doesn't seem to to work on OS 10.10+.
- name: Set desktop wallpaper image
  shell: sqlite3 ~/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '{{ ext_prefs_path_common }}/wallpaper/vlad_1920x1080.png'"
  tags: no_ci

# - name: Ensure osx.sh is executable
#   file:
#     path: ./roles/osx/files/osx.sh
#     mode: 0755

# # Bash told to run as if in a login shell.
# # Also lets the script know that it's Ansible running it.
# # TODO: `--ansible` option is playing up.
# - name: Execute osx.sh
#   shell: bash -lc ./roles/osx/files/osx.sh --ansible
#   become: true
#   notify:
#     - killall

- include: osx_defaults.yml

- debug: msg="Please log out and log back in for all settings to take effect."
