---

# plists
# ------------------------------------------------------------------------------

- name: Gather stats on all possible plist file locations
  stat: path={{ item[0] }}/{{ item[1] }}
  with_nested:
    - "{{ osx_plist_source_dirs }}"
    - "{{ osx_plists }}"
  register: osx_plist_files
  when: item[0] != ""

# Only copies items where a source file actually exists.
- name: Copy plist files to ~/Library/Preferences
  copy:
    src: "{{ item[0].stat.path }}"
    dest: ~/Library/Preferences/{{ item[1] }}
  with_nested:
    - "{{ osx_plist_files.results }}"
    - "{{ osx_plists }}"
  when: item[0].stat.path is defined
  notify:
    - killall

# defaults
# ------------------------------------------------------------------------------

# Sources:
# - https://mths.be/osx
# - https://github.com/geerlingguy/dotfiles/blob/master/.osx

# TODO: Currently avoiding "type: string" commands until this issue is resolved:
# https://github.com/ansible/ansible-modules-extras/issues/1742

# TODO: Currently avoiding "type: array" commands until they begin to behave.

- include: activity_monitor.yml
- include: dock_mission_control.yml
- include: finder.yml
- include: general_ui_ux.yml
- include: safari_webkit.yml
- include: screen.yml
- include: ssd.yml
- include: spotlight.yml
- include: terminal.yml
- include: textedit.yml
- include: time_machine.yml
- include: trackpad_mouse.yml
