---

- name: Gather stats on all possible plist file locations
  stat: path={{ item[0] }}/{{ item[1] }}
  with_nested:
    - "{{ osx_plist_source_dirs }}"
    - "{{ osx_plists }}"
  register: osx_plist_files
  when: item[0] != ""

# Only copies items where a source file actually exists.
- name: Copy plist files to ~/Library/Preferences
  copy:
    src: "{{ item[0].stat.path }}"
    dest: ~/Library/Preferences/{{ item[1] }}
  with_nested:
    - "{{ osx_plist_files.results }}"
    - "{{ osx_plists }}"
  when: item[0].stat.path is defined

- name: Ensure osx.sh is executable
  file:
    path: ./roles/osx/files/osx.sh
    mode: 0755

- include: osx_defaults.yml

# TODO: Not idempotent
# Bash told to run as if in a login shell.
- name: Execute osx.sh
  shell: bash -lc ./roles/osx/files/osx.sh --no-restart
  notify:
    - killall

- debug: msg="Done. Note that some of these changes require a logout/restart to take effect."
