---

# TODO: Avoid "type: string" commands until this issue is resolved:
# https://github.com/ansible/ansible-modules-extras/issues/1742

# General UI/UX
# ------------------------------------------------------------------------------

# Possible values: `WhenScrolling`, `Automatic` and `Always`
# - name: Always show scrollbars
#   osx_defaults:
#     domain: NSGlobalDomain
#     key: AppleShowScrollBars
#     type: string
#     value: "Always"
#   notify:
#     - killall

- name: Expand save panel by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true
  notify:
    - killall

- name: Expand print panel by default
  osx_defaults:
    domain: NSGlobalDomain
    key: PMPrintingExpandedStateForPrint
    type: bool
    value: true
  notify:
    - killall

- name: Save to disk (not to iCloud) by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
  notify:
    - killall

- name: Automatically quit printer app once the print jobs complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key: "Quit When Finished"
    type: bool
    value: true
  notify:
    - killall

- name: Disable the “Are you sure you want to open this application?” dialog
  osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
  notify:
    - killall

# - name: Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window
#   osx_defaults:
#     domain: /Library/Preferences/com.apple.loginwindow
#     key: AdminHostInfo
#     type: string
#     value: HostName
#   become: true
#   notify:
#     - killall

- name: Check for software updates daily, not just once per week
  osx_defaults:
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    type: int
    value: 1
  notify:
    - killall

- name: Disable smart quotes as they’re annoying when typing code
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
  notify:
    - killall

- name: Disable smart dashes as they’re annoying when typing code
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
  notify:
    - killall

# SSD-specific tweaks
# ------------------------------------------------------------------------------

# - name: Disable the sudden motion sensor as it’s not useful for SSDs
#   command: pmset -a sms 0
#   become: true

# Trackpad, mouse, keyboard, Bluetooth accessories, and input
# ------------------------------------------------------------------------------


# Screen
# ------------------------------------------------------------------------------


# Finder
# ------------------------------------------------------------------------------


# Dock, Dashboard, and hot corners
# ------------------------------------------------------------------------------


# Safari & WebKit
# ------------------------------------------------------------------------------


# Mail
# ------------------------------------------------------------------------------


# Spotlight
# ------------------------------------------------------------------------------


# Terminal
# ------------------------------------------------------------------------------


# Activity Monitor
# ------------------------------------------------------------------------------


# TextEdit
# ------------------------------------------------------------------------------


# Messages
# ------------------------------------------------------------------------------
