---

# TODO: Avoid "type: string" commands until this issue is resolved:
# https://github.com/ansible/ansible-modules-extras/issues/1742

- include: activity_monitor.yml
- include: dock_mission_control.yml
- include: finder.yml
- include: general_ui_ux.yml
- include: safari_webkit.yml
- include: screen.yml
- include: spotlight.yml
- include: terminal.yml
- include: textedit.yml
- include: time_machine.yml
